---
apiVersion: v1 
kind: Pod
metadata: 
  name: hema
  labels: 
    app: caddy
    env: production
spec:
  containers:
    - name: hema
      image: mysql:8.0
      ports:
        - name: hema
          containerPort: 3306
          protocol: TCP
      volumeMounts:
        - name: mysql-volume
          mountPath: /var/lib/mysql
      env:
        - name: MYSQL_ROOT_PASSWORD 
          value: admin
        - name: MYSQL_DATABASE
          value: students
        - name: MYSQL_USER
          value: hemachaitanya
        - name: MYSQL_PASSWORD
          value: admin
  volumes: 
    - name: mysql-volume
      persistentVolumeClaim: 
        claimName: mysql-pvc 
---
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels: 
    name: mysql-pvc
    env: production
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: managed  