---
apiVersion: v1
kind: 	Pod
metadata:
  name: apache
spec:
  containers:
    - name: httpd
      image: httpd:latest
      ports:
        - containerPort: 80
          hostPort: 80
    - name: nginx
      image: tomcat9
      ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Pod
metadata: 
  name: restart 
  labels: 
    app: jenkins
    auther: hema
spec:
  restartPolicy: OnFailure 
  containers: 
    - name: jenkins 
      image: jenkins/jenkins
      ports:
        - containerPort: 8080
      resources:
        requests:
          cpu: 0.05
          memory: 100Mi
        limits:
          cpu: 0.05
          memory: 256Mi
---
apiVersion: rbac/v1beta1
kind: Role
metadata:
  name: hema
  labels: 
    env: rolebased
    auth: hema
rules:
  - apiGroups: [""]
    resources: ["Pod"]
    verbs: ["get","list","watch"]
---
#### 
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hema
  namespace: dev
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
  
---
apiVersion: rbac/v1beta1
kind: RoleBinding
metadata:
  name: hema
  labels:
    env: rolebased
    auth: hema 
subjects:
  - kind: User 
    name: dev
roleRef:
  apiGroup: ""
  kind: Role
  name: hema


  ####

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hema
  namespace: dev
subjects:
- kind: User
  name: hema         ### <USERNAME>
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: hema
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1 
kind: Pod 
metadata:
  name: hema
  labels:
    app: web-app
    env: uat
spec:
  containers: 
    - name: webapplication 
      image: caddy 
      ports: 
        - containerPort: 80 
          protocol: TCP 
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: hema-svc
spec:
  selector:
    app: web-app
  ports: 
    - name: rama
      port: 80 
      targetPort: 80
      protocol: TCP 
  type: ClusterIP 
    




      

  
      

